services:
  - type: web
    name: mileninikolaci
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn moj_sajt.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
